[build]
# Build configuration for Railway deployment
builder = "nixpacks"

[deploy]
# Deployment configuration
startCommand = "python main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Health check configuration
healthcheckPath = "/health"
healthcheckTimeout = 300

[env]
# Environment variables specific to Railway
# These will override variables in .env file

# Python configuration
PYTHONUNBUFFERED = "1"
PYTHONPATH = "."

# Railway specific
PORT = "${{ PORT }}"
RAILWAY_ENVIRONMENT = "${{ RAILWAY_ENVIRONMENT }}"

# Database (Railway will provide PostgreSQL)
# DATABASE_URL will be automatically set by Railway when you add a PostgreSQL service

# Web interface
WEB_HOST = "0.0.0.0"
WEB_PORT = "${{ PORT }}"

# Enable features for production
ENABLE_WEB_INTERFACE = "true"
ENABLE_LOGGING = "true"

# Production logging
LOG_LEVEL = "INFO"
LOG_FILE = "/tmp/bot.log"

# Disable debug in production
DEBUG = "false"
WEB_DEBUG = "false"

[variables]
# Railway-specific variables
# You can set these in the Railway dashboard
# DISCORD_TOKEN = "your_bot_token"
# WEB_SECRET_KEY = "your_secret_key"
# WEB_API_KEY = "your_api_key"
# OWNER_IDS = "your_discord_user_id"